service: kintone-alchemist

custom:
  defaultStage: prod
  defaultDomain: {xxxx}.cybozu.com # Your kintone URL
  defaultAuth: {xxxxxx} # Your AUTH (LoginID:Password base64 encode)
  defaultSpaceID: {xx} # Your Space ID
  defaultThreadID: {xx} # Your Thread ID

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  timeout: 15
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource:
        - "*"
  environment:
    CYBOZU_DOMAIN: ${self:custom.defaultDomain}
    CYBOZU_AUTH: ${self:custom.defaultAuth}
    SPACE_ID: ${self:custom.defaultSpaceID}
    THREAD_ID: ${self:custom.defaultThreadID}

functions:
  func:
    handler: handler.main
    description: 錬kin術
    events:
      - http:
          path: renkin
          method: post
          cors: true
    environment:
      FUNCTION_NAME: ${self:service}-${self:provider.stage}